name: Docker Caffe Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and save the caffe Docker image
      run: |
        docker build . --file hub/caffe.Dockerfile --tag xinetzone/caffe-conda
        # docker load -i caffe-conda.tar
        mkdir -p .temp/
        cd .temp/
        # docker run -it --rm xinetzone/caffe-conda conda run -n py312 python3 -m nuitka --module caffe --include-package=caffe 
        docker save xinetzone/caffe-conda -o "caffe-conda.tar"

    - name: Compress the TAR files
      run: tar -czvf xinetzone-images.tar.gz .temp/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: caffe-conda-tar
        path: xinetzone-images.tar.gz
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Clean up intermediate files
      run: |
        rm -rf .temp/
