name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # - name: Build and save the caffe Docker image
    #   run: |
    #     docker build . --file hub/caffe.Dockerfile --tag xinetzone/caffe-base:$(date +%s)
    #     docker save xinetzone/caffe-base -o "xinetzone-caffe-base.tar"

    # - name: Compress the TAR files
    #   run: tar -czf xinetzone-images.tar.gz *.tar

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: xinetzone-images-tar
    #     path: xinetzone-images.tar.gz
    #     retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    # - name: Clean up intermediate files
    #   run: |
    #     rm *.tar
