name: Docker TVM 打包 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and save the caffe Docker image
      run: |
        docker build . --file hub/tvm-pag.Dockerfile --tag xinetzone/tvm-pag
        # docker load -i caffe-conda.tar
        mkdir -p .temp/
        cd .temp/
        docker save xinetzone/tvm-pag -o "tvm-pag.tar"

    - name: Compress the TAR files
      run: tar -czvf xinetzone-images.tar.gz .temp/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: caffe-conda-tar
        path: xinetzone-images.tar.gz
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Clean up intermediate files
      run: |
        rm -rf .temp/
